services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PRIVATE_KEY: ${PRIVATE_KEY}
      RPC_URL: ${RPC_URL}
      ORACLE_ADDRESS: ${ORACLE_ADDRESS}
      DB_URL: ${DB_URL}
    ports:
      - 8000:8000
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
volumes:
  db-data:
